---
title: ""
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

# **Challenge: The 12 Days of Christmas**

```{r library}
library(english)
library(glue)
library(dplyr)
library(tidyverse)
```

```{r data_read}
xmas <- read.csv("https://www.dropbox.com/s/12ipnczn0fygglt/xmas.csv?dl=1")
xmas2 <- read.csv("https://www.dropbox.com/s/tmilnd6ad8k26wy/xmas2.csv?dl=1")
```

Re-write your functions to be pipe-friendly. That is, make them so that

xmas %>%
  sing_verse(3, Day.in.Words, Gift.Item)

xmas %>%
  sing_xmas_song(???)
both work (but with appropriate arguments in the ??? part)

```{r make_phrase}
make_phrase <- function(num, gift) {
  num <- english(num)
  return(glue("{num} {gift}"))
}


make_phrase(num = 10, 
            gift = "lords a-leaping")
```

```{r gift_phrase}
xmas <- xmas %>%
  mutate(
    Gift_Phrase = map2_chr(Day, Gift.Item, make_phrase)
  )
```

```{r sing_verse}
sing_verse <- function(data, num, day, gift) {

  day <- data %>% 
    pull({{day}})
  
  gift <- data %>% 
    pull({{gift}})
  
  seq= seq(num,1,by =-1)
  print(glue::glue("On the {day[num]} day of Christmas, my true love sent to me,"))
  return(map2_chr(seq, gift[seq], make_phrase) %>%
           cat(sep = ", \n"))
  
}

xmas %>% sing_verse(3, Day.in.Words, Gift.Item)
```

```{r sing_xmas_song_1}
sing_xmas_song <- function(data, num, day, gift) {
  for (i in 12:1) {
    data %>% sing_verse(i, {{day}}, {{gift}})
    cat("\n")
  }

}

xmas %>% sing_xmas_song(num, day =Day.in.Words,gift = Gift.Item)
```

